version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Tus3cr3tP@ssw0rd
    ports:
      - "1433:1433"
    networks:
      - backend

networks:
  backend:
    driver: bridge
